import {describe, expect, it, vi} from 'vitest';
vi.mock('obsidian', () => ({parseYaml: (text: string) => Object.fromEntries(text.split('\n').filter(Boolean).map(line => { const [key, ...rest] = line.split(':'); return [key.trim(), rest.join(':').trim().replace(/^['"]|['"]$/g, '')]; }))}));
import {GraphStore} from '../src/store';
type Entry={path:string;extension:string;stat:{size:number};text:string};
class Vault { files=new Map<string,Entry>(); writes=0; fail=false; getFiles(){return [...this.files.values()];} getAbstractFileByPath(p:string){return this.files.get(p);} async read(f:Entry){return f.text;} async createFolder(p:string){if(!this.files.has(p))this.files.set(p,this.make(p,''));} async create(p:string,t:string){if(this.fail)throw Error('disk');const f=this.make(p,t);this.files.set(p,f);this.writes++;return f;} async process(f:Entry,fn:(s:string)=>string){if(this.fail)throw Error('disk');f.text=fn(f.text);this.writes++;return f;} make(path:string,text:string):Entry{return {path,text,extension:path.split('.').pop()??'',stat:{size:text.length}};}}
function fm(t:string){const m=t.match(/^---\n([\s\S]*?)\n---/),o:Record<string,unknown>={};for(const l of m?.[1].split('\n')??[]){const [k,...v]=l.split(':');if(k)o[k.trim()]=v.join(':').trim().replace(/^['"]|['"]$/g,'');}return o;}
function app(v:Vault){return {vault:v,metadataCache:{getFileCache:(f:Entry)=>({frontmatter:fm(f.text)})},fileManager:{renameFile:async(f:Entry,path:string)=>{v.files.delete(f.path);f.path=path;v.files.set(path,f);v.writes++;},processFrontMatter:async(f:Entry,fn:(x:Record<string,unknown>)=>void)=>{const x=fm(f.text);fn(x);const body=f.text.replace(/^---\n[\s\S]*?\n---\n?/,'');f.text=`---\n${Object.entries(x).map(([k,z])=>`${k}: ${JSON.stringify(z)}`).join('\n')}\n---\n${body}`;}}} as never;}
const image=(id:string,path=`${id}.png`)=>({id,path,x:0,y:0,width:240,height:240});
const region=(id:string,imageId:string)=>({id,imageId,label:'r',shape:{type:'rect' as const,x:0,y:0,width:1,height:1},properties:{}});
describe('GraphStore persistence safety',()=>{
 it('loads 20k without writes and preserves missing',async()=>{const v=new Vault();for(let i=0;i<20000;i++)v.files.set(`i${i}.png`,v.make(`i${i}.png`,''));const s=new GraphStore(app(v),()=>{});await s.load();expect(s.getSnapshot().images).toHaveLength(20000);expect(v.writes).toBe(0);v.files.delete('i42.png');await s.refreshCatalog();await s.refreshCatalog();expect(s.getSnapshot().images.filter(x=>x.path==='i42.png')).toHaveLength(1);});
 it('preserves concurrent same-shard writes',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();await Promise.all([s.upsertImage(image('img-a','a.png')),s.upsertImage(image('img-b','b.png'))]);const r=new GraphStore(app(v),()=>{});await r.load();expect(r.getSnapshot().images.map(x=>x.path).sort()).toEqual(['a.png','b.png']);});
 it('rejects corrupt reload without replacing snapshot',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();await s.upsertImage(image('a'));const before=s.getSnapshot(),f=[...v.files.values()].find(x=>x.path.includes('/images-'))!;f.text='{bad';const writes=v.writes;await expect(s.load()).rejects.toThrow();expect(s.getSnapshot()).toEqual(before);expect(v.writes).toBe(writes);});
 it('does not mutate memory on failed write',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();v.fail=true;await expect(s.upsertImage(image('a'))).rejects.toThrow();expect(s.getSnapshot().images).toHaveLength(0);});
 it('creates wikilink companion and rejects unowned collision',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();await s.upsertImage(image('a','folder/a.png'));await s.ensureCompanion('a');expect(v.files.get('_Image Graph/Notes/folder/a.md')?.text).toContain('[[folder/a.png]]');v.files.set('_Image Graph/Notes/b.md',v.make('_Image Graph/Notes/b.md','---\ntitle: User\n---\nKeep body'));await s.upsertImage(image('b'));await s.ensureCompanion('b');expect(v.files.get('_Image Graph/Notes/b.md')?.text).toContain('Keep body');expect(v.files.get('_Image Graph/Notes/b (png).md')?.text).toContain('image_graph_id');});
 it('handles metadata deletion and reserved keys',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();await s.upsertImage(image('a'));await s.writeMetadata('a',{'old key':'x',keep:true});await s.writeMetadata('a',{keep:false});const t=v.files.get('_Image Graph/Notes/a.md')?.text??'';expect(t).not.toContain('old key');expect(t).toContain('image_graph_id');});
 it('removes incident edges and preserves unrelated images',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();await s.upsertImage(image('a'));await s.upsertImage(image('b'));await s.upsertRegion(region('r','a'));await s.upsertEdge({id:'e',source:{imageId:'a',regionId:'r'},target:{imageId:'b'},direction:'none',properties:{}});await s.removeRegion('r');expect(s.getSnapshot().regions).toHaveLength(0);expect(s.getSnapshot().edges).toHaveLength(0);expect(s.getSnapshot().images).toHaveLength(2);});
 it('rejects malformed shapes',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();await s.upsertImage(image('a'));await expect(s.upsertRegion({...region('x','a'),shape:{type:'rect',x:0,y:0,width:NaN,height:1}})).rejects.toThrow();await expect(s.upsertRegion({...region('y','a'),shape:{type:'polygon',points:[{x:0,y:0}]}})).rejects.toThrow();});
 it('writes every moved image, not only the first',async()=>{const v=new Vault();let notified=0;const s=new GraphStore(app(v),()=>{notified++;});await s.load();
  const ids=['img-a','img-b','img-c','img-d'];
  await s.upsertImages(ids.map(id=>image(id,`${id}.png`)));
  notified=0;const writes=v.writes;
  await s.upsertImages(ids.map((id,index)=>({...image(id,`${id}.png`),x:40*(index+1),y:80})));
  expect(notified).toBe(1);
  expect(v.writes-writes).toBeLessThanOrEqual(ids.length);
  const reloaded=new GraphStore(app(v),()=>{});await reloaded.load();
  expect(reloaded.getSnapshot().images.filter(x=>x.y===80).map(x=>x.x).sort((a,b)=>a-b)).toEqual([40,80,120,160]);
 });
 it('writes a connection into both companion notes and removes it with the edge',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();
  await s.upsertImage(image('a'));await s.upsertImage(image('b'));
  await s.upsertEdge({id:'e',source:{imageId:'a'},target:{imageId:'b'},direction:'forward',properties:{relation:'resembles'}});
  expect(v.files.get('_Image Graph/Notes/a.md')?.text).toContain('[[_Image Graph/Notes/b|→ resembles · b]]');
  expect(v.files.get('_Image Graph/Notes/b.md')?.text).toContain('[[_Image Graph/Notes/a|← resembles · a]]');
  await s.writeMetadata('a',{caption:'kept'});
  expect(v.files.get('_Image Graph/Notes/a.md')?.text).toContain('_Image Graph/Notes/b');
  await s.removeEdge('e');
  expect(v.files.get('_Image Graph/Notes/a.md')?.text).not.toContain('connections');
  expect(v.files.get('_Image Graph/Notes/a.md')?.text).toContain('caption');
 });
 it('backfills connection links for a vault connected by an earlier version',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();
  await s.upsertImage(image('a'));await s.upsertImage(image('b'));
  await s.upsertEdge({id:'e',source:{imageId:'a'},target:{imageId:'b'},direction:'none',properties:{relation:'resembles'}});
  for(const id of ['a','b']){const note=v.files.get(`_Image Graph/Notes/${id}.md`)!;note.text=note.text.split('\n').filter(line=>!line.startsWith('connections')).join('\n');}
  expect(v.files.get('_Image Graph/Notes/a.md')?.text).not.toContain('connections');
  const reloaded=new GraphStore(app(v),()=>{});await reloaded.load();await reloaded.syncCompanionLinks();
  expect(v.files.get('_Image Graph/Notes/a.md')?.text).toContain('[[_Image Graph/Notes/b|resembles · b]]');
 });
 it('gives each picture its own width and leaves a placed image where it is',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();
  for(const name of ['a','b','c'])v.files.set(`${name}.png`,v.make(`${name}.png`,''));
  await s.refreshCatalog();
  const before=s.getSnapshot().images;
  expect(before.every(x=>x.width===240&&x.height===240)).toBe(true);
  const placed=before.find(x=>x.path==='b.png')!;
  await s.upsertImage({...placed,x:4000,y:4000,pinned:true});
  await s.applyPixelSizes(new Map([['a.png',{width:1600,height:400}],['c.png',{width:400,height:1600}]]));
  const after=new Map(s.getSnapshot().images.map(x=>[x.path,x]));
  expect(after.get('a.png')).toMatchObject({width:960,height:240});
  expect(after.get('c.png')).toMatchObject({width:60,height:240});
  expect(after.get('b.png')).toMatchObject({x:4000,y:4000,pinned:true});
  const wide=after.get('a.png')!,tall=after.get('c.png')!;
  expect(wide.x+wide.width<=tall.x||tall.x+tall.width<=wide.x||wide.y+wide.height<=tall.y||tall.y+tall.height<=wide.y).toBe(true);
 });
 it('undoes a region deletion together with the connections it took',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();
  await s.upsertImage(image('a'));await s.upsertImage(image('b'));
  await s.upsertRegion(region('r','a'));
  await s.upsertEdge({id:'e',source:{imageId:'a',regionId:'r'},target:{imageId:'b'},direction:'none',properties:{relation:'shows'}});
  await s.removeRegion('r');
  expect(s.getSnapshot().regions).toHaveLength(0);expect(s.getSnapshot().edges).toHaveLength(0);
  expect(await s.undo()).toBe('delete a region');
  expect(s.getSnapshot().regions.map(x=>x.id)).toEqual(['r']);
  expect(s.getSnapshot().edges.map(x=>x.id)).toEqual(['e']);
  const reloaded=new GraphStore(app(v),()=>{});await reloaded.load();
  expect(reloaded.getSnapshot().edges).toHaveLength(1);
  expect(await s.redo()).toBe('delete a region');
  expect(s.getSnapshot().regions).toHaveLength(0);expect(s.getSnapshot().edges).toHaveLength(0);
 });
 it('undoes a move of several images at once',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();
  await s.upsertImages([image('a'),image('b')]);
  await s.upsertImages([{...image('a'),x:400},{...image('b'),x:800}]);
  expect(await s.undo()).toBe('change 2 images');
  expect(s.getSnapshot().images.map(x=>x.x)).toEqual([0,0]);
  expect(await s.redo()).toBe('change 2 images');
  expect(s.getSnapshot().images.map(x=>x.x)).toEqual([400,800]);
 });
 it('undoes a drawn region by taking it away again',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();
  await s.upsertImage(image('a'));await s.upsertRegion(region('r','a'));
  expect(s.historyLabels().undo).toBe('draw a region');
  expect(await s.undo()).toBe('draw a region');
  expect(s.getSnapshot().regions).toHaveLength(0);
  const reloaded=new GraphStore(app(v),()=>{});await reloaded.load();
  expect(reloaded.getSnapshot().regions).toHaveLength(0);
 });
 it('keeps the derived layout out of the history',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();
  for(const name of ['a','b'])v.files.set(`${name}.png`,v.make(`${name}.png`,''));
  await s.refreshCatalog();
  await s.applyPixelSizes(new Map([['a.png',{width:1600,height:400}]]));
  await s.syncCompanionLinks();
  expect(s.historyLabels()).toEqual({undo:null,redo:null});
  expect(await s.undo()).toBeNull();
 });
 it('gives a moved image back to the grid, and can undo that too',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();
  for(const name of ['a','b','c'])v.files.set(`${name}.png`,v.make(`${name}.png`,''));
  await s.refreshCatalog();
  const placed=s.getSnapshot().images.find(x=>x.path==='b.png')!;
  await s.upsertImage({...placed,x:9000,y:9000,pinned:true});
  expect(s.getSnapshot().images.filter(x=>x.pinned)).toHaveLength(1);
  expect(await s.unpinImages()).toBe(1);
  const released=s.getSnapshot().images.find(x=>x.path==='b.png')!;
  expect(released.pinned).toBeUndefined();
  expect(released.x).not.toBe(9000);
  expect(await s.unpinImages()).toBe(0);
  expect(await s.undo()).toBe('return images to the grid');
  expect(s.getSnapshot().images.filter(x=>x.pinned)).toHaveLength(1);
 });
 it('renames an old id-named companion after its picture, keeping the body and the links',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();
  for(const name of ['Photos/harbour','Photos/crane'])v.files.set(`${name}.png`,v.make(`${name}.png`,''));
  await s.refreshCatalog();
  const byPath=new Map(s.getSnapshot().images.map(x=>[x.path,x]));
  const a=byPath.get('Photos/harbour.png')!,b=byPath.get('Photos/crane.png')!;
  // An earlier version's layout: an opaque name, under the folder that used to hold them.
  for(const im of [a,b]){
   const old=`_Image Graph/Images/${im.id}.md`;
   v.files.set(old,v.make(old,`---\nimage: "[[${im.path}]]"\nimage_graph_id: ${im.id}\n---\nThe owner wrote this about ${im.path}.\n`));
   await s.upsertImage({...im,metadataPath:old});
  }
  await s.upsertEdge({id:'e',source:{imageId:a.id},target:{imageId:b.id},direction:'none',properties:{relation:'resembles'}});
  expect(await s.migrateCompanions()).toBe(2);
  const moved=v.files.get('_Image Graph/Notes/Photos/harbour.md');
  expect(moved).toBeDefined();
  expect(moved!.text).toContain('The owner wrote this about Photos/harbour.png.');
  expect(v.files.get(`_Image Graph/Images/${a.id}.md`)).toBeUndefined();
  expect(s.getSnapshot().images.find(x=>x.id===a.id)?.metadataPath).toBe('_Image Graph/Notes/Photos/harbour.md');
  // The connections link on the other end now points at the new address.
  expect(v.files.get('_Image Graph/Notes/Photos/crane.md')?.text).toContain('_Image Graph/Notes/Photos/harbour');
  // Idempotent: a second run has nothing to move.
  expect(await s.migrateCompanions()).toBe(0);
 });
 it('keeps identity across source, companion, and folder renames',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();v.files.set('old/a.png',v.make('old/a.png',''));await s.refreshCatalog();const before=s.getSnapshot().images[0];await s.ensureCompanion(before.id);const note=v.files.get('_Image Graph/Notes/old/a.md')!;v.files.delete('old/a.png');v.files.set('new/a.png',v.make('new/a.png',''));await s.renamePath('old','new');v.files.delete(note.path);v.files.set('_Image Graph/Notes/old/a.md',v.make('_Image Graph/Notes/old/a.md',note.text));await s.renamePath('_Image Graph/Images','_Image Graph/Notes');const reloaded=new GraphStore(app(v),()=>{});await reloaded.load();const after=reloaded.getSnapshot().images.find(x=>x.id===before.id)!;expect(after.path).toBe('new/a.png');expect(after.metadataPath).toContain('_Image Graph/Notes');});
 it('shows foreign regions, refuses to write them, and lets a connection reach one',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();
  await s.upsertImage(image('a'));await s.upsertImage(image('b'));
  const foreign={...region('ia-r1','a'),label:'Sky',origin:'image-annotation'};
  let notified=0;const t=new GraphStore(app(v),()=>{notified++;});await t.load();notified=0;
  t.setForeignRegions([foreign]);expect(notified).toBe(1);
  t.setForeignRegions([foreign]);expect(notified).toBe(1);
  expect(t.getSnapshot().regions).toEqual([foreign]);
  expect(() => t.setForeignRegions([region('own','a')])).toThrow('origin');
  await expect(t.upsertRegion({...foreign,label:'Renamed'})).rejects.toThrow('Image Annotation');
  await expect(t.removeRegion('ia-r1')).rejects.toThrow('Image Annotation');
  await t.upsertEdge({id:'e',source:{imageId:'b'},target:{imageId:'a',regionId:'ia-r1'},direction:'forward',properties:{relation:'shows'}});
  expect(v.files.get('_Image Graph/Notes/b.md')?.text).toContain('→ shows · a');
  // Nothing foreign reached a shard, and a reload keeps the foreign map beside the reloaded own records.
  expect([...v.files.values()].filter(f=>f.path.includes('/regions-'))).toHaveLength(0);
  await t.load();expect(t.getSnapshot().regions.map(r=>r.id)).toEqual(['ia-r1']);
  expect(t.getSnapshot().edges).toHaveLength(1);
 });
 it('removes only the connections whose foreign region is gone, and can undo it',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();
  await s.upsertImage(image('a'));await s.upsertImage(image('b'));await s.upsertRegion(region('own','b'));
  s.setForeignRegions([{...region('ia-r1','a'),origin:'image-annotation'},{...region('ia-r2','a'),origin:'image-annotation'}]);
  await s.upsertEdge({id:'e1',source:{imageId:'b'},target:{imageId:'a',regionId:'ia-r1'},direction:'none',properties:{}});
  await s.upsertEdge({id:'e2',source:{imageId:'b',regionId:'own'},target:{imageId:'a',regionId:'ia-r2'},direction:'none',properties:{}});
  await s.upsertEdge({id:'e3',source:{imageId:'b',regionId:'own'},target:{imageId:'a'},direction:'none',properties:{}});
  expect(await s.removeDanglingRegionEdges()).toBe(0);
  s.setForeignRegions([{...region('ia-r2','a'),origin:'image-annotation'}]);
  expect(await s.removeDanglingRegionEdges()).toBe(1);
  expect(s.getSnapshot().edges.map(e=>e.id).sort()).toEqual(['e2','e3']);
  expect(v.files.get('_Image Graph/Notes/a.md')?.text).toContain('connections');
  expect(await s.undo()).toBe('remove connections to deleted regions');
  expect(s.getSnapshot().edges.map(e=>e.id).sort()).toEqual(['e1','e2','e3']);
 });
 it('writes annotation links only into companions that exist, removes them when gone, and never invents a note',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();
  await s.upsertImage(image('a'));await s.upsertImage(image('b'));await s.ensureCompanion('a');
  const links=new Map([['a',['[[Essay#^x|Sky · Essay]]']],['b',['[[Essay|Sea · Essay]]']]]);
  await s.syncAnnotationLinks(links);
  expect(v.files.get('_Image Graph/Notes/a.md')?.text).toContain('Sky · Essay');
  expect(v.files.get('_Image Graph/Notes/b.md')).toBeUndefined();
  await s.writeMetadata('a',{caption:'kept'});
  expect(v.files.get('_Image Graph/Notes/a.md')?.text).toContain('Sky · Essay');
  await s.syncAnnotationLinks(new Map());
  expect(v.files.get('_Image Graph/Notes/a.md')?.text).not.toContain('annotations');
  expect(v.files.get('_Image Graph/Notes/a.md')?.text).toContain('caption');
 });
 it('tells a web snapshot where it came from, names its companion after the note, and keeps an owner\u2019s edit',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();
  const web=image('w','Image Annotation/Media/0123abcd.png');await s.upsertImage(web);
  s.setForeignRegions([{...region('ia-r1','w'),origin:'image-annotation'}],new Map([['w',{originalUrl:'https://x.test/a.png',articlePath:'Clips/Essay.md'}]]));
  const file=await s.ensureCompanion('w');
  expect(file.path).toBe('_Image Graph/Notes/Image Annotation/Media/Essay.md');
  await s.syncAnnotationLinks(new Map());
  const text=()=>v.files.get(file.path)?.text??'';
  expect(text()).toContain('source_url: "https://x.test/a.png"');
  expect(text()).toContain('[[Clips/Essay]]');
  v.files.get(file.path)!.text=text().replace('https://x.test/a.png','https://owner.test/edited.png');
  await s.syncAnnotationLinks(new Map());
  expect(text()).toContain('owner.test');
 });

});
