import {describe, expect, it, vi} from 'vitest';
vi.mock('obsidian', () => ({parseYaml: (text: string) => Object.fromEntries(text.split('\n').filter(Boolean).map(line => { const [key, ...rest] = line.split(':'); return [key.trim(), rest.join(':').trim().replace(/^['"]|['"]$/g, '')]; }))}));
import {GraphStore} from '../src/store';
type Entry={path:string;extension:string;stat:{size:number};text:string};
class Vault { files=new Map<string,Entry>(); writes=0; fail=false; getFiles(){return [...this.files.values()];} getAbstractFileByPath(p:string){return this.files.get(p);} async read(f:Entry){return f.text;} async createFolder(p:string){if(!this.files.has(p))this.files.set(p,this.make(p,''));} async create(p:string,t:string){if(this.fail)throw Error('disk');const f=this.make(p,t);this.files.set(p,f);this.writes++;return f;} async process(f:Entry,fn:(s:string)=>string){if(this.fail)throw Error('disk');f.text=fn(f.text);this.writes++;return f;} make(path:string,text:string):Entry{return {path,text,extension:path.split('.').pop()??'',stat:{size:text.length}};}}
function fm(t:string){const m=t.match(/^---\n([\s\S]*?)\n---/),o:Record<string,unknown>={};for(const l of m?.[1].split('\n')??[]){const [k,...v]=l.split(':');if(k)o[k.trim()]=v.join(':').trim().replace(/^['"]|['"]$/g,'');}return o;}
function app(v:Vault){return {vault:v,metadataCache:{getFileCache:(f:Entry)=>({frontmatter:fm(f.text)})},fileManager:{processFrontMatter:async(f:Entry,fn:(x:Record<string,unknown>)=>void)=>{const x=fm(f.text);fn(x);const body=f.text.replace(/^---\n[\s\S]*?\n---\n?/,'');f.text=`---\n${Object.entries(x).map(([k,z])=>`${k}: ${JSON.stringify(z)}`).join('\n')}\n---\n${body}`;}}} as never;}
const image=(id:string,path=`${id}.png`)=>({id,path,x:0,y:0,width:240,height:240});
const region=(id:string,imageId:string)=>({id,imageId,label:'r',shape:{type:'rect' as const,x:0,y:0,width:1,height:1},properties:{}});
describe('GraphStore persistence safety',()=>{
 it('loads 20k without writes and preserves missing',async()=>{const v=new Vault();for(let i=0;i<20000;i++)v.files.set(`i${i}.png`,v.make(`i${i}.png`,''));const s=new GraphStore(app(v),()=>{});await s.load();expect(s.getSnapshot().images).toHaveLength(20000);expect(v.writes).toBe(0);v.files.delete('i42.png');await s.refreshCatalog();await s.refreshCatalog();expect(s.getSnapshot().images.filter(x=>x.path==='i42.png')).toHaveLength(1);});
 it('preserves concurrent same-shard writes',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();await Promise.all([s.upsertImage(image('img-a','a.png')),s.upsertImage(image('img-b','b.png'))]);const r=new GraphStore(app(v),()=>{});await r.load();expect(r.getSnapshot().images.map(x=>x.path).sort()).toEqual(['a.png','b.png']);});
 it('rejects corrupt reload without replacing snapshot',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();await s.upsertImage(image('a'));const before=s.getSnapshot(),f=[...v.files.values()].find(x=>x.path.includes('/images-'))!;f.text='{bad';const writes=v.writes;await expect(s.load()).rejects.toThrow();expect(s.getSnapshot()).toEqual(before);expect(v.writes).toBe(writes);});
 it('does not mutate memory on failed write',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();v.fail=true;await expect(s.upsertImage(image('a'))).rejects.toThrow();expect(s.getSnapshot().images).toHaveLength(0);});
 it('creates wikilink companion and rejects unowned collision',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();await s.upsertImage(image('a','folder/a.png'));await s.ensureCompanion('a');expect(v.files.get('_Image Graph/Images/a.md')?.text).toContain('[[folder/a.png]]');v.files.set('_Image Graph/Images/b.md',v.make('_Image Graph/Images/b.md','---\ntitle: User\n---\nKeep body'));await s.upsertImage(image('b'));await expect(s.ensureCompanion('b')).rejects.toThrow();expect(v.files.get('_Image Graph/Images/b.md')?.text).toContain('Keep body');});
 it('handles metadata deletion and reserved keys',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();await s.upsertImage(image('a'));await s.writeMetadata('a',{'old key':'x',keep:true});await s.writeMetadata('a',{keep:false});const t=v.files.get('_Image Graph/Images/a.md')?.text??'';expect(t).not.toContain('old key');expect(t).toContain('image_graph_id');});
 it('removes incident edges and preserves unrelated images',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();await s.upsertImage(image('a'));await s.upsertImage(image('b'));await s.upsertRegion(region('r','a'));await s.upsertEdge({id:'e',source:{imageId:'a',regionId:'r'},target:{imageId:'b'},direction:'none',properties:{}});await s.removeRegion('r');expect(s.getSnapshot().regions).toHaveLength(0);expect(s.getSnapshot().edges).toHaveLength(0);expect(s.getSnapshot().images).toHaveLength(2);});
 it('rejects malformed shapes',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();await s.upsertImage(image('a'));await expect(s.upsertRegion({...region('x','a'),shape:{type:'rect',x:0,y:0,width:NaN,height:1}})).rejects.toThrow();await expect(s.upsertRegion({...region('y','a'),shape:{type:'polygon',points:[{x:0,y:0}]}})).rejects.toThrow();});
 it('keeps identity across source, companion, and folder renames',async()=>{const v=new Vault(),s=new GraphStore(app(v),()=>{});await s.load();v.files.set('old/a.png',v.make('old/a.png',''));await s.refreshCatalog();const before=s.getSnapshot().images[0];await s.ensureCompanion(before.id);const note=v.files.get('_Image Graph/Images/'+encodeURIComponent(before.id)+'.md')!;v.files.delete('old/a.png');v.files.set('new/a.png',v.make('new/a.png',''));await s.renamePath('old','new');v.files.delete(note.path);v.files.set('_Image Graph/Notes/'+encodeURIComponent(before.id)+'.md',v.make('_Image Graph/Notes/'+encodeURIComponent(before.id)+'.md',note.text));await s.renamePath('_Image Graph/Images','_Image Graph/Notes');const reloaded=new GraphStore(app(v),()=>{});await reloaded.load();const after=reloaded.getSnapshot().images.find(x=>x.id===before.id)!;expect(after.path).toBe('new/a.png');expect(after.metadataPath).toContain('_Image Graph/Notes');});
});
